version: '3'  # Docker Compose 파일의 버전. v3은 대부분의 기능을 지원하며 프로덕션 환경에서도 자주 사용됨.

services:
  springboot-app:  # 서비스 이름 (컨테이너 역할 명시)
    image: ${DOCKER_USERNAME}/cicd-app:latest  # 사용할 도커 이미지. GitHub Actions에서 푸시한 최신 버전 사용
    container_name: cicd_app  # 실제 생성될 컨테이너의 이름 지정

    ports:
      - "8080:8080"  # 호스트의 8080 포트를 컨테이너의 8080 포트에 매핑 (외부에서 접속 가능)

    environment:  # 컨테이너에 전달할 환경변수 설정
      MYSQL_URL: ${MYSQL_URL}                  # DB 접속 URL
      MYSQL_USER: ${MYSQL_USER}                # DB 사용자명
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}        # DB 비밀번호
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Asia/Seoul -Dfile.encoding=UTF-8"  # JVM 시간대/인코딩 설정
      SPRING_PROFILES_ACTIVE: prod             # Spring Boot의 프로파일을 prod(운영)로 설정

    networks:
      - mynet  # 동일한 네트워크에 연결된 다른 컨테이너들과 통신 가능

networks:
  mynet:
    external: true  # 이미 생성된 외부 네트워크(mynet 등)를 사용. docker network create mynet 필요
